language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer config -g platform.php $TRAVIS_PHP_VERSION
  - composer update

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
